<a href="https://colab.research.google.com/github/prachitrocks/prachitrocks-LetsUpgrade-AI-ML/blob/master/Copy_of_Numpy_Assignment_Questions_23_july_2020_Lets_Upgrade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Create a 3x3x3 array with random values 

In [ ]:
import numpy as np
x=np.random.random((3,3,3))
print(x)

[[[0.70273313 0.58970769 0.96741843]
  [0.0383946  0.77093825 0.84840726]
  [0.35891474 0.12594284 0.55732332]]

 [[0.50169007 0.1135379  0.87097234]
  [0.42395798 0.05360344 0.40758879]
  [0.9388255  0.53645038 0.24516277]]

 [[0.46344137 0.31382009 0.85433487]
  [0.56057904 0.573759   0.22136022]
  [0.02624317 0.53451588 0.57362124]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [ ]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.18155283 0.72282078 0.21349249 0.40576242 0.18552859]
 [0.26107831 0.97412087 0.43853851 0.61704489 0.87885173]
 [0.03730501 0.68917327 0.54991547 0.00988907 0.64023358]
 [0.93512117 0.47202177 0.00512162 0.78259388 0.26193644]
 [0.82380302 0.8069572  0.58049764 0.06618879 0.40723638]]
After normalization:
[[0.1820757  0.74066018 0.21503719 0.41345832 0.18617865]
 [0.2641454  1.         0.447283   0.63150026 0.90168295]
 [0.03321303 0.7059362  0.56222319 0.00491998 0.65543081]
 [0.95975259 0.48183747 0.         0.80234557 0.26503098]
 [0.8448731  0.82748833 0.59378376 0.06302087 0.41497943]]


# 5.  How to find common values between two arrays?

In [ ]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 60, 30]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 60, 30]
Common values between two arrays:
[10 60]


# 6.How to get the dates of yesterday, today and tomorrow?

In [ ]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [ ]:
import numpy as np
x = np.random.randint(1,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 1 1 1 1]
Second array:
[1 1 0 0 1 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [ ]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.63266393 0.14906945 0.00524439 0.80135116 0.7579072  0.42452066
 0.9638873  0.21462585 0.34578041 0.96376063]
Maximum value replaced by 0:
[0.63266393 0.14906945 0.00524439 0.80135116 0.7579072  0.42452066
 0.         0.21462585 0.34578041 0.96376063]


# 9. How to print all the values of an array?

In [ ]:
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [ ]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(1, 4)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.27550224 0.44612666 0.68620701 0.52416701]]

Subtract the mean of each row of the said matrix:

[[-0.20749849 -0.03687407  0.20320628  0.04116628]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [15]:
import numpy as np

In [16]:
a=np.random.randint(1,8,8)
b=np.random.randint(a)
print("Vector b is ",b)
print("Vector a is ",a)
c= []
b.sort()
for x in b:
  if x not in c:
    c.append(x)

for y in c:
  a[y] +=1 
print(a)   

Vector b is  [5 2 6 0 1 1 1 0]
Vector a is  [7 3 7 6 7 2 3 1]
[8 4 8 6 7 3 4 1]


# 12.How to get the diagonal of a dot product?

In [ ]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
np.diag(np.dot(A, B))

array([ 80, 120, 126])

# 13.How to find the most frequent value in an array?

In [ ]:
import numpy as np
x = np.random.randint(0, 20, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[12 10 16  7  4  3 19 17 11 18 10 13  3  8  9  7 11  3  6 19  3 11 13 19
 16  0 11  0 14 19  5 11 16 19 10 12  8 12 19 10]
Most frequent value in the above array:
19


# 14.How to get the n largest values of an array

In [ ]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [ ]:
import numpy as np
arra1 = np.array([("prachit Reyaan", 88.5, 90),
                 ("Ana anil", 87, 99),
             ("Jordy Prachiti", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['prachit Reyaan' '88.5' '90']
 ['Ana anil' '87' '99']
 ['Jordy Prachiti' '85.5' '91']]

Record array;
[(b'prachit Reyaan', 88.5, 90) (b'Ana anil', 87. , 99)
 (b'Jordy Prachiti', 85.5, 91)]


In [ ]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
